### ISSUE TITLE
Request for a code snippet to use DeepOnto

### ISSUE THREAD

**Issue by ocorcho** [ralharbi868/RETROFIT-CQs#1]
I am trying to follow the steps required for the CQ generation from one of my ontologies.

Would it be possible to have a code snippet for the first step that uses the DeepOnto library so as to prepare it for the second step?

**Comment by SemTech23** [comment]
Hello Oscar, Thank you for your interest in Retrofit-CQ. Regarding the Deeponto code, the link will be sent to you privately via email, along with an updated link for this repository, as it will be made private due to ongoing improvements in the code.

Cheers!
Reham
